title: "Hieu Trung Nguyen"
description: "Personal academic website of Hieu Trung Nguyen, a PhD student at The Chinese University of Hong Kong."
url: "https://hieunt91.github.io"
baseurl: ""
locale: "en-US"
timezone: "Asia/Hong_Kong"
theme: null

author:
  name: "Hieu Trung Nguyen"
  avatar: "/images/HieuNT.jpg"
  bio: "SEEM PhD Student @ CUHK"
  location: "Ha Noi - Viet Nam"
  employer: "Chinese University of Hong Kong"
  email: "hilljun.2000@gmail.com"
  scholar: "https://scholar.google.com/citations?hl=en&user=OlFCFKgAAAAJ"
  github: "https://github.com/HieuNT91"
  resume: "/resume/Hieu_Resume.pdf"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
